/* Month grid, the day panel, and the event editor.

   Repeating events are generated by the store, so a cell may hold occurrences
   that share one underlying record. An edit therefore has to ask what it
   applies to: this day only, or the whole series. */
window.CalendarView = (function () {
  'use strict';

  var WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  var MAX_CHIPS = 3;

  var els = {};
  var viewMonth;          // Date pinned to the 1st of the month on screen
  var selectedDate;       // 'YYYY-MM-DD'
  var editingId = null;
  var editingMaster = null;
  var occurrenceDate = '';
  var lastFocused = null;

  var MODES = ['day', 'week', 'month', 'year', 'agenda'];
  var mode = 'month';
  var narrow = window.matchMedia('(max-width: 560px)');

  /* ---------------------------------------------------------- formatting -- */

  function formatMonth(date) {
    return date.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
  }

  function formatDayLabel(key) {
    var date = Store.fromKey(key);
    // Long names wrap on a phone, so abbreviate there.
    var label = date.toLocaleDateString(undefined, narrow.matches
      ? { weekday: 'short', day: 'numeric', month: 'short' }
      : { weekday: 'long', day: 'numeric', month: 'long' });
    if (key === Store.todayKey()) return 'Today · ' + label;
    return label;
  }

  function formatTime(time) {
    return Fmt.time(time);
  }

  /* ------------------------------------------------------------ rendering -- */

  function renderWeekdays() {
    els.weekdays.innerHTML = '';
    WEEKDAYS.forEach(function (name) {
      var cell = document.createElement('div');
      cell.textContent = name;
      els.weekdays.appendChild(cell);
    });
  }

  function renderGrid() {
    var year = viewMonth.getFullYear();
    var month = viewMonth.getMonth();
    var start = new Date(year, month, 1);
    var leading = start.getDay();
    start.setDate(1 - leading);                      // back up to the Sunday
    var today = Store.todayKey();

    // Five or six weeks, whichever the month actually needs.
    var daysInMonth = new Date(year, month + 1, 0).getDate();
    var cells = Math.ceil((leading + daysInMonth) / 7) * 7;

    var first = Store.toKey(start);
    var last = Store.toKey(new Date(start.getFullYear(), start.getMonth(), start.getDate() + cells - 1));

    var byDate = {};
    Store.eventsInRange(first, last).forEach(function (item) {
      (byDate[item.date] = byDate[item.date] || []).push(item);
    });
    var tasksByDate = {};
    Store.allTasks({ openOnly: true }).forEach(function (task) {
      if (task.due >= first && task.due <= last) {
        (tasksByDate[task.due] = tasksByDate[task.due] || []).push(task);
      }
    });

    els.grid.innerHTML = '';
    var fragment = document.createDocumentFragment();

    for (var i = 0; i < cells; i++) {
      var date = new Date(start.getFullYear(), start.getMonth(), start.getDate() + i);
      var key = Store.toKey(date);
      var events = byDate[key] || [];
      var tasks = tasksByDate[key] || [];

      var cell = document.createElement('button');
      cell.type = 'button';
      cell.className = 'day';
      cell.dataset.date = key;
      cell.setAttribute('role', 'gridcell');
      if (date.getMonth() !== month) cell.classList.add('is-outside');
      if (date.getDay() === 0 || date.getDay() === 6) cell.classList.add('is-weekend');
      if (key === today) cell.classList.add('is-today');
      if (key === selectedDate) {
        cell.classList.add('is-selected');
        cell.setAttribute('aria-current', 'date');
      }

      var parts = [date.toLocaleDateString(undefined, { day: 'numeric', month: 'long' })];
      if (events.length) parts.push(events.length + (events.length === 1 ? ' event' : ' events'));
      if (tasks.length) parts.push(tasks.length + (tasks.length === 1 ? ' task' : ' tasks'));
      cell.setAttribute('aria-label', parts.join(', '));

      var number = document.createElement('span');
      number.className = 'day-number';
      number.textContent = date.getDate();
      cell.appendChild(number);

      events.slice(0, MAX_CHIPS).forEach(function (item) {
        var chip = document.createElement('span');
        chip.className = 'day-chip';
        if (item.color) chip.dataset.color = item.color;
        chip.textContent = item.time ? formatTime(item.time) + ' ' + item.title : item.title;
        cell.appendChild(chip);
      });
      tasks.slice(0, Math.max(0, MAX_CHIPS - events.length)).forEach(function (task) {
        var chip = document.createElement('span');
        chip.className = 'day-chip is-task';
        chip.textContent = '☐ ' + task.title;
        cell.appendChild(chip);
      });

      var hidden = events.length + tasks.length - MAX_CHIPS;
      if (hidden > 0) {
        var more = document.createElement('span');
        more.className = 'day-more';
        more.textContent = '+' + hidden + ' more';
        cell.appendChild(more);
      }

      // Narrow screens show dots instead of chips (see the stylesheet).
      if (events.length || tasks.length) {
        var dots = document.createElement('span');
        dots.className = 'day-dots';
        if (events.length) {
          var eventDot = document.createElement('span');
          eventDot.className = 'day-dot';
          dots.appendChild(eventDot);
        }
        if (tasks.length) {
          var taskDot = document.createElement('span');
          taskDot.className = 'day-dot is-task';
          dots.appendChild(taskDot);
        }
        cell.appendChild(dots);
      }

      fragment.appendChild(cell);
    }

    els.grid.appendChild(fragment);
  }

  // Sunday of the week a date falls in.
  function weekStart(key) {
    return Store.shiftKey(key, -Store.fromKey(key).getDay());
  }

  // What is on each day of a range, gathered in one pass.
  function gather(firstKey, lastKey) {
    var events = {};
    Store.eventsInRange(firstKey, lastKey).forEach(function (item) {
      (events[item.date] = events[item.date] || []).push(item);
    });
    var tasks = {};
    Store.allTasks({ openOnly: true }).forEach(function (task) {
      if (task.due >= firstKey && task.due <= lastKey) {
        (tasks[task.due] = tasks[task.due] || []).push(task);
      }
    });
    return { events: events, tasks: tasks };
  }

  // A week as seven columns, each the day's own little list. Not an hour grid:
  // an hour grid spends most of its height on the hours nobody has anything in.
  function renderWeek() {
    var start = weekStart(selectedDate);
    var end = Store.shiftKey(start, 6);
    var found = gather(start, end);
    var today = Store.todayKey();

    els.weekGrid.innerHTML = '';
    var fragment = document.createDocumentFragment();

    for (var i = 0; i < 7; i++) {
      var key = Store.shiftKey(start, i);
      var date = Store.fromKey(key);
      var events = found.events[key] || [];
      var tasks = found.tasks[key] || [];

      var column = document.createElement('button');
      column.type = 'button';
      column.className = 'week-day';
      column.dataset.date = key;
      column.setAttribute('role', 'gridcell');
      if (key === today) column.classList.add('is-today');
      if (key === selectedDate) {
        column.classList.add('is-selected');
        column.setAttribute('aria-current', 'date');
      }
      if (date.getDay() === 0 || date.getDay() === 6) column.classList.add('is-weekend');

      var head = document.createElement('span');
      head.className = 'week-day-head';
      var name = document.createElement('span');
      name.textContent = WEEKDAYS[date.getDay()];
      var number = document.createElement('span');
      number.className = 'week-day-number';
      number.textContent = date.getDate();
      head.appendChild(name);
      head.appendChild(number);
      column.appendChild(head);

      events.forEach(function (item) {
        var chip = document.createElement('span');
        chip.className = 'day-chip';
        if (item.color) chip.dataset.color = item.color;
        // The time is its own span so a narrow column can drop it: on a phone
        // "7:0..." says nothing, where the title at least names the thing.
        if (item.time) {
          var when = document.createElement('span');
          when.className = 'chip-time';
          when.textContent = formatTime(item.time);
          chip.appendChild(when);
        }
        chip.appendChild(document.createTextNode(item.title));
        column.appendChild(chip);
      });
      tasks.forEach(function (task) {
        var chip = document.createElement('span');
        chip.className = 'day-chip is-task';
        chip.textContent = '\u2610 ' + task.title;
        column.appendChild(chip);
      });
      if (!events.length && !tasks.length) {
        var blank = document.createElement('span');
        blank.className = 'week-day-blank';
        blank.textContent = '—';
        column.appendChild(blank);
      }

      fragment.appendChild(column);
    }
    els.weekGrid.appendChild(fragment);
  }

  // Twelve months at a glance. Days carry a dot when something is on, which is
  // all a year can usefully say in the space a year gets.
  function renderYear() {
    var year = viewMonth.getFullYear();
    var found = gather(year + '-01-01', year + '-12-31');
    var today = Store.todayKey();

    els.yearGrid.innerHTML = '';
    var fragment = document.createDocumentFragment();

    for (var month = 0; month < 12; month++) {
      var block = document.createElement('div');
      block.className = 'year-month';

      var title = document.createElement('button');
      title.type = 'button';
      title.className = 'year-month-name';
      title.dataset.month = String(month);
      title.textContent = new Date(year, month, 1)
        .toLocaleDateString(undefined, { month: 'long' });
      block.appendChild(title);

      var grid = document.createElement('div');
      grid.className = 'year-days';

      WEEKDAYS.forEach(function (name) {
        var head = document.createElement('span');
        head.className = 'year-weekday';
        head.textContent = name.charAt(0);
        grid.appendChild(head);
      });

      var leading = new Date(year, month, 1).getDay();
      for (var blankIndex = 0; blankIndex < leading; blankIndex++) {
        grid.appendChild(document.createElement('span'));
      }

      var days = new Date(year, month + 1, 0).getDate();
      for (var day = 1; day <= days; day++) {
        var key = Store.toKey(new Date(year, month, day));
        var cell = document.createElement('button');
        cell.type = 'button';
        cell.className = 'year-day';
        cell.dataset.date = key;
        cell.textContent = day;
        if (key === today) cell.classList.add('is-today');
        var busyEvents = (found.events[key] || []).length;
        var busyTasks = (found.tasks[key] || []).length;
        if (busyEvents || busyTasks) {
          cell.classList.add('is-busy');
          cell.setAttribute('aria-label', day + ': ' +
            [busyEvents ? busyEvents + ' events' : '', busyTasks ? busyTasks + ' tasks' : '']
              .filter(Boolean).join(', '));
        }
        grid.appendChild(cell);
      }

      block.appendChild(grid);
      fragment.appendChild(block);
    }
    els.yearGrid.appendChild(fragment);
  }

  function renderDayPanel() {
    els.dayLabel.textContent = formatDayLabel(selectedDate);
    els.dayEvents.innerHTML = '';

    var events = Store.eventsOn(selectedDate);
    if (!events.length) {
      var empty = document.createElement('li');
      empty.className = 'empty';
      empty.textContent = 'Nothing planned yet.';
      els.dayEvents.appendChild(empty);
    } else {
      events.forEach(function (item) {
        var row = document.createElement('li');
        var button = document.createElement('button');
        button.type = 'button';
        button.className = 'event-item';
        button.dataset.id = item.id;
        if (item.color) button.dataset.color = item.color;

        var time = document.createElement('span');
        time.className = 'event-time';
        time.textContent = formatTime(item.time);

        var body = document.createElement('span');
        body.className = 'event-body';
        var title = document.createElement('span');
        title.className = 'event-title';
        title.textContent = item.title;
        body.appendChild(title);
        if (item.repeating) {
          var repeat = document.createElement('span');
          repeat.className = 'repeat-mark';
          repeat.textContent = 'repeats';
          title.appendChild(document.createTextNode(' '));
          title.appendChild(repeat);
        }
        if (item.details) {
          var details = document.createElement('p');
          details.className = 'event-details';
          details.textContent = item.details;
          body.appendChild(details);
        }

        button.appendChild(time);
        button.appendChild(body);
        row.appendChild(button);
        els.dayEvents.appendChild(row);
      });
    }

    // Tasks due that day sit under the schedule, so one screen answers
    // "what is happening" and "what do I owe" for the selected date.
    var tasks = Store.tasksOn(selectedDate);
    els.dayTasksWrap.hidden = !tasks.length;
    if (tasks.length) TasksView.fillList(els.dayTasks, tasks, '', { hideDueFor: selectedDate });
  }

  // Three weeks of everything, in one list. A month grid answers "what does
  // this month look like"; this answers "what is coming".
  function renderAgenda() {
    var start = Store.todayKey();
    var end = Store.shiftKey(start, 20);

    var byDate = {};
    Store.eventsInRange(start, end).forEach(function (item) {
      (byDate[item.date] = byDate[item.date] || { events: [], tasks: [] }).events.push(item);
    });
    Store.allTasks({ openOnly: true }).forEach(function (task) {
      if (!task.due) return;
      // Anything already overdue belongs on today, not in the past.
      var key = task.due < start ? start : task.due;
      if (key > end) return;
      (byDate[key] = byDate[key] || { events: [], tasks: [] }).tasks.push(task);
    });

    els.agendaBody.innerHTML = '';
    var days = Object.keys(byDate).sort();
    if (!days.length) {
      var empty = document.createElement('p');
      empty.className = 'empty';
      empty.textContent = 'Nothing in the next three weeks.';
      els.agendaBody.appendChild(empty);
      return;
    }

    days.forEach(function (key) {
      var group = document.createElement('section');
      group.className = 'agenda-day';

      var heading = document.createElement('h3');
      heading.className = 'agenda-date';
      heading.textContent = formatDayLabel(key);
      if (key === Store.todayKey()) heading.classList.add('is-today');
      group.appendChild(heading);

      var list = document.createElement('ul');
      list.className = 'event-list';
      byDate[key].events.forEach(function (item) {
        var row = document.createElement('li');
        var button = document.createElement('button');
        button.type = 'button';
        button.className = 'event-item';
        button.dataset.id = item.id;
        button.dataset.date = item.date;
        if (item.color) button.dataset.color = item.color;

        var time = document.createElement('span');
        time.className = 'event-time';
        time.textContent = formatTime(item.time);
        var body = document.createElement('span');
        body.className = 'event-body';
        var title = document.createElement('span');
        title.className = 'event-title';
        title.textContent = item.title;
        body.appendChild(title);
        button.appendChild(time);
        button.appendChild(body);
        row.appendChild(button);
        list.appendChild(row);
      });
      group.appendChild(list);

      if (byDate[key].tasks.length) {
        var tasks = document.createElement('ul');
        tasks.className = 'task-list';
        TasksView.fillList(tasks, byDate[key].tasks, '', { hideDueFor: key });
        TasksView.wireList(tasks);
        group.appendChild(tasks);
      }

      els.agendaBody.appendChild(group);
    });
  }

  // A span of days has to read naturally whatever order the locale puts the
  // fields in, so this is built from the parts rather than glued together:
  // "13 – 19 September 2026" here, "September 13 – 19, 2026" in the US.
  function spanLabel(start, end) {
    var full = { day: 'numeric', month: 'long', year: 'numeric' };
    var sameYear = start.getFullYear() === end.getFullYear();

    if (sameYear && start.getMonth() === end.getMonth()) {
      // Only the day differs, so the first day goes in front of the last one
      // wherever in the string the locale happens to have put it.
      var first = start.toLocaleDateString(undefined, { day: 'numeric' });
      return new Intl.DateTimeFormat(undefined, full).formatToParts(end)
        .map(function (part) {
          return part.type === 'day' ? first + ' – ' + part.value : part.value;
        }).join('');
    }

    // Crossing a month, the year is only worth saying once unless it changes too.
    return start.toLocaleDateString(undefined, sameYear ? { day: 'numeric', month: 'long' } : full) +
      ' – ' + end.toLocaleDateString(undefined, full);
  }

  // What the bar over the grid says, which is different for every mode.
  function rangeLabel() {
    if (mode === 'day') return formatDayLabel(selectedDate);
    if (mode === 'year') return String(viewMonth.getFullYear());
    if (mode === 'week') {
      return spanLabel(Store.fromKey(weekStart(selectedDate)),
        Store.fromKey(Store.shiftKey(weekStart(selectedDate), 6)));
    }
    return formatMonth(viewMonth);
  }

  // Back and forward move by whatever the mode is showing.
  function step(direction) {
    if (mode === 'day') selectedDate = Store.shiftKey(selectedDate, direction);
    else if (mode === 'week') selectedDate = Store.shiftKey(selectedDate, direction * 7);
    else if (mode === 'year') {
      viewMonth = new Date(viewMonth.getFullYear() + direction, viewMonth.getMonth(), 1);
    } else {
      viewMonth = new Date(viewMonth.getFullYear(), viewMonth.getMonth() + direction, 1);
    }
    // Day and week move the selection, so the month has to follow it.
    if (mode === 'day' || mode === 'week') {
      var moved = Store.fromKey(selectedDate);
      viewMonth = new Date(moved.getFullYear(), moved.getMonth(), 1);
    }
    render();
  }

  function render() {
    if (mode === 'agenda') {
      renderAgenda();
      return;
    }
    if (mode === 'week') renderWeek();
    else if (mode === 'year') renderYear();
    else if (mode === 'month') renderGrid();

    els.monthLabel.textContent = rangeLabel();
    if (mode !== 'year') renderDayPanel();
  }

  function setMode(next) {
    mode = MODES.indexOf(next) === -1 ? 'month' : next;

    els.agenda.hidden = mode !== 'agenda';
    els.monthLayout.hidden = mode === 'agenda';
    els.monthLayout.dataset.mode = mode;

    // One card holds whichever grid the mode wants; the day panel comes along
    // for every mode that is about a day or a handful of them.
    els.grid.hidden = mode !== 'month';
    els.weekGrid.hidden = mode !== 'week';
    els.yearGrid.hidden = mode !== 'year';
    els.weekdays.hidden = mode !== 'month';

    Array.prototype.forEach.call(els.modes.querySelectorAll('[data-mode]'), function (chip) {
      chip.classList.toggle('is-on', chip.dataset.mode === mode);
    });
    render();
  }

  /* --------------------------------------------------------- event modal -- */

  function renderSwatches(selected) {
    els.colors.innerHTML = '';
    [''].concat(Store.colors()).forEach(function (name) {
      var swatch = document.createElement('button');
      swatch.type = 'button';
      swatch.className = 'swatch' + (name === selected ? ' is-on' : '');
      swatch.dataset.color = name;
      swatch.setAttribute('role', 'radio');
      swatch.setAttribute('aria-checked', name === selected ? 'true' : 'false');
      swatch.setAttribute('aria-label', name || 'Default');
      els.colors.appendChild(swatch);
    });
  }

  function chosenColor() {
    var on = els.colors.querySelector('.swatch.is-on');
    return on ? on.dataset.color : '';
  }

  function showScope(show) {
    els.scope.hidden = !show;
    if (show) els.scope.querySelector('input[value="occurrence"]').checked = true;
  }

  function currentScope() {
    if (els.scope.hidden) return 'series';
    var chosen = els.scope.querySelector('input[name="scope"]:checked');
    return chosen ? chosen.value : 'series';
  }

  function syncUntilField() {
    els.until.parentNode.hidden = !els.repeat.value;
  }

  function openModal(eventId, dateKey, occurrence) {
    editingId = eventId || null;
    editingMaster = eventId ? Store.getEvent(eventId) : null;
    occurrenceDate = occurrence || dateKey || selectedDate;
    lastFocused = document.activeElement;

    els.modalTitle.textContent = editingMaster ? 'Edit event' : 'New event';
    els.eventTitle.value = editingMaster ? editingMaster.title : '';
    els.eventDate.value = editingMaster
      ? (editingMaster.repeat ? occurrenceDate : editingMaster.date)
      : (dateKey || selectedDate);
    els.eventTime.value = editingMaster ? (editingMaster.time || '') : '';
    els.eventDetails.value = editingMaster ? (editingMaster.details || '') : '';
    els.repeat.value = editingMaster ? (editingMaster.repeat || '') : '';
    els.until.value = editingMaster ? (editingMaster.repeatUntil || '') : '';
    renderSwatches(editingMaster ? (editingMaster.color || '') : '');
    els.remind.value = String(editingMaster && typeof editingMaster.remind === 'number'
      ? editingMaster.remind
      : Store.getSettings().defaultRemind);
    els.eventDelete.hidden = !editingMaster;
    els.eventError.hidden = true;

    syncUntilField();
    showScope(!!(editingMaster && editingMaster.repeat));

    els.modal.hidden = false;
    els.eventTitle.focus();
  }

  function closeModal() {
    els.modal.hidden = true;
    editingId = null;
    editingMaster = null;
    if (lastFocused && document.contains(lastFocused)) lastFocused.focus();
    lastFocused = null;
  }

  function showError(message) {
    els.eventError.textContent = message;
    els.eventError.hidden = false;
  }

  function submit(submitEvent) {
    submitEvent.preventDefault();
    var title = els.eventTitle.value.trim();
    var date = els.eventDate.value;

    if (!title) return showError('Give the event a title.');
    // Safari on older iOS has no date picker widget, so validate the text.
    if (!Store.isKey(date)) return showError('Pick a valid date.');
    if (els.until.value && !Store.isKey(els.until.value)) return showError('Pick a valid end date.');
    if (els.repeat.value && els.until.value && els.until.value < date) {
      return showError('The repeat cannot end before it starts.');
    }

    var scope = currentScope();
    Store.saveEvent({
      id: editingId,
      scope: scope,
      occurrenceDate: occurrenceDate,
      title: title,
      date: date,
      time: els.eventTime.value || '',
      details: els.eventDetails.value.trim(),
      color: chosenColor(),
      remind: Number(els.remind.value),
      repeat: els.repeat.value,
      repeatUntil: els.repeat.value ? els.until.value : '',
      // A new rule makes the old list of skipped days meaningless.
      resetSkips: !!(editingMaster && editingMaster.repeat !== els.repeat.value)
    });

    selectedDate = date;
    var moved = Store.fromKey(date);
    viewMonth = new Date(moved.getFullYear(), moved.getMonth(), 1);
    closeModal();
    render();
  }

  function removeEvent() {
    if (!editingId) return;
    var repeating = editingMaster && editingMaster.repeat;
    var scope = repeating ? currentScope() : 'series';

    var message = repeating && scope === 'occurrence'
      ? 'Remove just this day from the series?'
      : (repeating ? 'Delete the whole repeating event?' : 'Delete this event?');
    if (!window.confirm(message)) return;

    Store.deleteEvent(editingId, scope, occurrenceDate);
    closeModal();
    render();
  }

  /* ----------------------------------------------------------------- api -- */

  function init() {
    els = {
      grid: document.getElementById('day-grid'),
      weekdays: document.getElementById('weekday-row'),
      monthLabel: document.getElementById('month-label'),
      dayLabel: document.getElementById('day-label'),
      dayEvents: document.getElementById('day-events'),
      dayTasks: document.getElementById('day-tasks'),
      dayTasksWrap: document.getElementById('day-tasks-wrap'),
      modal: document.getElementById('event-modal'),
      modalTitle: document.getElementById('event-modal-title'),
      eventTitle: document.getElementById('event-title'),
      eventDate: document.getElementById('event-date'),
      eventTime: document.getElementById('event-time'),
      eventDetails: document.getElementById('event-details'),
      eventDelete: document.getElementById('event-delete'),
      eventError: document.getElementById('event-error'),
      repeat: document.getElementById('event-repeat'),
      until: document.getElementById('event-until'),
      scope: document.getElementById('event-scope'),
      colors: document.getElementById('event-colors'),
      remind: document.getElementById('event-remind'),
      agenda: document.getElementById('agenda'),
      agendaBody: document.getElementById('agenda-body'),
      monthLayout: document.getElementById('month-layout'),
      weekGrid: document.getElementById('week-grid'),
      yearGrid: document.getElementById('year-grid'),
      modes: document.getElementById('calendar-modes')
    };

    selectedDate = Store.todayKey();
    viewMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);

    renderWeekdays();
    TasksView.wireList(els.dayTasks);

    // Rotating a phone switches between the long and short day label.
    if (narrow.addEventListener) narrow.addEventListener('change', renderDayPanel);
    else if (narrow.addListener) narrow.addListener(renderDayPanel);

    document.getElementById('prev-month').addEventListener('click', function () { step(-1); });
    document.getElementById('next-month').addEventListener('click', function () { step(1); });
    document.getElementById('add-event').addEventListener('click', function () {
      openModal(null, selectedDate);
    });

    els.weekGrid.addEventListener('click', function (clickEvent) {
      var column = clickEvent.target.closest('.week-day');
      if (!column) return;
      selectedDate = column.dataset.date;
      render();
    });

    els.yearGrid.addEventListener('click', function (clickEvent) {
      var name = clickEvent.target.closest('.year-month-name');
      if (name) {
        // A month's name is a way into that month.
        viewMonth = new Date(viewMonth.getFullYear(), Number(name.dataset.month), 1);
        selectedDate = Store.toKey(viewMonth);
        setMode('month');
        return;
      }
      var cell = clickEvent.target.closest('.year-day');
      if (!cell) return;
      selectedDate = cell.dataset.date;
      var picked = Store.fromKey(selectedDate);
      viewMonth = new Date(picked.getFullYear(), picked.getMonth(), 1);
      setMode('day');
    });

    els.grid.addEventListener('click', function (clickEvent) {
      var cell = clickEvent.target.closest('.day');
      if (!cell) return;
      selectedDate = cell.dataset.date;
      var date = Store.fromKey(selectedDate);
      if (date.getMonth() !== viewMonth.getMonth() || date.getFullYear() !== viewMonth.getFullYear()) {
        viewMonth = new Date(date.getFullYear(), date.getMonth(), 1);
      }
      render();
    });

    els.grid.addEventListener('dblclick', function (clickEvent) {
      var cell = clickEvent.target.closest('.day');
      if (cell) openModal(null, cell.dataset.date);
    });

    els.dayEvents.addEventListener('click', function (clickEvent) {
      var item = clickEvent.target.closest('.event-item');
      if (item) openModal(item.dataset.id, selectedDate, selectedDate);
    });

    els.repeat.addEventListener('change', syncUntilField);

    els.colors.addEventListener('click', function (clickEvent) {
      var swatch = clickEvent.target.closest('.swatch');
      if (swatch) renderSwatches(swatch.dataset.color);
    });

    els.modes.addEventListener('click', function (clickEvent) {
      var chip = clickEvent.target.closest('[data-mode]');
      if (chip) setMode(chip.dataset.mode);
    });

    document.getElementById('agenda-add').addEventListener('click', function () {
      openModal(null, Store.todayKey());
    });

    els.agendaBody.addEventListener('click', function (clickEvent) {
      var item = clickEvent.target.closest('.event-item');
      if (item) openModal(item.dataset.id, item.dataset.date, item.dataset.date);
    });

    // Switching between "this day" and "the series" changes which date the
    // form is really editing.
    els.scope.addEventListener('change', function () {
      if (!editingMaster) return;
      els.eventDate.value = currentScope() === 'series' ? editingMaster.date : occurrenceDate;
    });

    document.getElementById('event-form').addEventListener('submit', submit);
    document.getElementById('event-cancel').addEventListener('click', closeModal);
    els.eventDelete.addEventListener('click', removeEvent);
    els.modal.addEventListener('mousedown', function (clickEvent) {
      if (clickEvent.target === els.modal) closeModal();
    });

    render();
  }

  return {
    init: init,
    render: render,
    isModalOpen: function () { return !els.modal.hidden; },
    closeModal: closeModal,
    goToday: function () {
      var now = new Date();
      selectedDate = Store.toKey(now);
      viewMonth = new Date(now.getFullYear(), now.getMonth(), 1);
      render();
    },
    selectDate: function (key) {
      selectedDate = key;
      var date = Store.fromKey(key);
      viewMonth = new Date(date.getFullYear(), date.getMonth(), 1);
      render();
    },
    newEvent: function (dateKey) { openModal(null, dateKey || selectedDate); },
    editEvent: function (id, date) { openModal(id, date, date); }
  };
})();
