/* Month grid, the day panel, and the event editor.

   Repeating events are generated by the store, so a cell may hold occurrences
   that share one underlying record. An edit therefore has to ask what it
   applies to: this day only, or the whole series. */
window.CalendarView = (function () {
  'use strict';

  var WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  var MAX_CHIPS = 3;

  var els = {};
  var viewMonth;          // Date pinned to the 1st of the month on screen
  var selectedDate;       // 'YYYY-MM-DD'
  var editingId = null;
  var editingMaster = null;
  var occurrenceDate = '';
  var lastFocused = null;

  var narrow = window.matchMedia('(max-width: 560px)');

  /* ---------------------------------------------------------- formatting -- */

  function formatMonth(date) {
    return date.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
  }

  function formatDayLabel(key) {
    var date = Store.fromKey(key);
    // Long names wrap on a phone, so abbreviate there.
    var label = date.toLocaleDateString(undefined, narrow.matches
      ? { weekday: 'short', day: 'numeric', month: 'short' }
      : { weekday: 'long', day: 'numeric', month: 'long' });
    if (key === Store.todayKey()) return 'Today · ' + label;
    return label;
  }

  function formatTime(time) {
    if (!time) return 'All day';
    var parts = time.split(':');
    var date = new Date(2000, 0, 1, Number(parts[0]), Number(parts[1]));
    return date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
  }

  /* ------------------------------------------------------------ rendering -- */

  function renderWeekdays() {
    els.weekdays.innerHTML = '';
    WEEKDAYS.forEach(function (name) {
      var cell = document.createElement('div');
      cell.textContent = name;
      els.weekdays.appendChild(cell);
    });
  }

  function renderGrid() {
    var year = viewMonth.getFullYear();
    var month = viewMonth.getMonth();
    var start = new Date(year, month, 1);
    var leading = start.getDay();
    start.setDate(1 - leading);                      // back up to the Sunday
    var today = Store.todayKey();

    // Five or six weeks, whichever the month actually needs.
    var daysInMonth = new Date(year, month + 1, 0).getDate();
    var cells = Math.ceil((leading + daysInMonth) / 7) * 7;

    var first = Store.toKey(start);
    var last = Store.toKey(new Date(start.getFullYear(), start.getMonth(), start.getDate() + cells - 1));

    var byDate = {};
    Store.eventsInRange(first, last).forEach(function (item) {
      (byDate[item.date] = byDate[item.date] || []).push(item);
    });
    var tasksByDate = {};
    Store.allTasks({ openOnly: true }).forEach(function (task) {
      if (task.due >= first && task.due <= last) {
        (tasksByDate[task.due] = tasksByDate[task.due] || []).push(task);
      }
    });

    els.grid.innerHTML = '';
    var fragment = document.createDocumentFragment();

    for (var i = 0; i < cells; i++) {
      var date = new Date(start.getFullYear(), start.getMonth(), start.getDate() + i);
      var key = Store.toKey(date);
      var events = byDate[key] || [];
      var tasks = tasksByDate[key] || [];

      var cell = document.createElement('button');
      cell.type = 'button';
      cell.className = 'day';
      cell.dataset.date = key;
      cell.setAttribute('role', 'gridcell');
      if (date.getMonth() !== month) cell.classList.add('is-outside');
      if (key === today) cell.classList.add('is-today');
      if (key === selectedDate) {
        cell.classList.add('is-selected');
        cell.setAttribute('aria-current', 'date');
      }

      var parts = [date.toLocaleDateString(undefined, { day: 'numeric', month: 'long' })];
      if (events.length) parts.push(events.length + (events.length === 1 ? ' event' : ' events'));
      if (tasks.length) parts.push(tasks.length + (tasks.length === 1 ? ' task' : ' tasks'));
      cell.setAttribute('aria-label', parts.join(', '));

      var number = document.createElement('span');
      number.className = 'day-number';
      number.textContent = date.getDate();
      cell.appendChild(number);

      events.slice(0, MAX_CHIPS).forEach(function (item) {
        var chip = document.createElement('span');
        chip.className = 'day-chip';
        chip.textContent = item.time ? formatTime(item.time) + ' ' + item.title : item.title;
        cell.appendChild(chip);
      });
      tasks.slice(0, Math.max(0, MAX_CHIPS - events.length)).forEach(function (task) {
        var chip = document.createElement('span');
        chip.className = 'day-chip is-task';
        chip.textContent = '☐ ' + task.title;
        cell.appendChild(chip);
      });

      var hidden = events.length + tasks.length - MAX_CHIPS;
      if (hidden > 0) {
        var more = document.createElement('span');
        more.className = 'day-more';
        more.textContent = '+' + hidden + ' more';
        cell.appendChild(more);
      }

      // Narrow screens show dots instead of chips (see the stylesheet).
      if (events.length || tasks.length) {
        var dots = document.createElement('span');
        dots.className = 'day-dots';
        if (events.length) {
          var eventDot = document.createElement('span');
          eventDot.className = 'day-dot';
          dots.appendChild(eventDot);
        }
        if (tasks.length) {
          var taskDot = document.createElement('span');
          taskDot.className = 'day-dot is-task';
          dots.appendChild(taskDot);
        }
        cell.appendChild(dots);
      }

      fragment.appendChild(cell);
    }

    els.grid.appendChild(fragment);
    els.monthLabel.textContent = formatMonth(viewMonth);
  }

  function renderDayPanel() {
    els.dayLabel.textContent = formatDayLabel(selectedDate);
    els.dayEvents.innerHTML = '';

    var events = Store.eventsOn(selectedDate);
    if (!events.length) {
      var empty = document.createElement('li');
      empty.className = 'empty';
      empty.textContent = 'Nothing planned yet.';
      els.dayEvents.appendChild(empty);
    } else {
      events.forEach(function (item) {
        var row = document.createElement('li');
        var button = document.createElement('button');
        button.type = 'button';
        button.className = 'event-item';
        button.dataset.id = item.id;

        var time = document.createElement('span');
        time.className = 'event-time';
        time.textContent = formatTime(item.time);

        var body = document.createElement('span');
        body.className = 'event-body';
        var title = document.createElement('span');
        title.className = 'event-title';
        title.textContent = item.title;
        body.appendChild(title);
        if (item.repeating) {
          var repeat = document.createElement('span');
          repeat.className = 'repeat-mark';
          repeat.textContent = 'repeats';
          title.appendChild(document.createTextNode(' '));
          title.appendChild(repeat);
        }
        if (item.details) {
          var details = document.createElement('p');
          details.className = 'event-details';
          details.textContent = item.details;
          body.appendChild(details);
        }

        button.appendChild(time);
        button.appendChild(body);
        row.appendChild(button);
        els.dayEvents.appendChild(row);
      });
    }

    // Tasks due that day sit under the schedule, so one screen answers
    // "what is happening" and "what do I owe" for the selected date.
    var tasks = Store.tasksOn(selectedDate);
    els.dayTasksWrap.hidden = !tasks.length;
    if (tasks.length) TasksView.fillList(els.dayTasks, tasks, '');
  }

  function render() {
    renderGrid();
    renderDayPanel();
  }

  /* --------------------------------------------------------- event modal -- */

  function showScope(show) {
    els.scope.hidden = !show;
    if (show) els.scope.querySelector('input[value="occurrence"]').checked = true;
  }

  function currentScope() {
    if (els.scope.hidden) return 'series';
    var chosen = els.scope.querySelector('input[name="scope"]:checked');
    return chosen ? chosen.value : 'series';
  }

  function syncUntilField() {
    els.until.parentNode.hidden = !els.repeat.value;
  }

  function openModal(eventId, dateKey, occurrence) {
    editingId = eventId || null;
    editingMaster = eventId ? Store.getEvent(eventId) : null;
    occurrenceDate = occurrence || dateKey || selectedDate;
    lastFocused = document.activeElement;

    els.modalTitle.textContent = editingMaster ? 'Edit event' : 'New event';
    els.eventTitle.value = editingMaster ? editingMaster.title : '';
    els.eventDate.value = editingMaster
      ? (editingMaster.repeat ? occurrenceDate : editingMaster.date)
      : (dateKey || selectedDate);
    els.eventTime.value = editingMaster ? (editingMaster.time || '') : '';
    els.eventDetails.value = editingMaster ? (editingMaster.details || '') : '';
    els.repeat.value = editingMaster ? (editingMaster.repeat || '') : '';
    els.until.value = editingMaster ? (editingMaster.repeatUntil || '') : '';
    els.eventDelete.hidden = !editingMaster;
    els.eventError.hidden = true;

    syncUntilField();
    showScope(!!(editingMaster && editingMaster.repeat));

    els.modal.hidden = false;
    els.eventTitle.focus();
  }

  function closeModal() {
    els.modal.hidden = true;
    editingId = null;
    editingMaster = null;
    if (lastFocused && document.contains(lastFocused)) lastFocused.focus();
    lastFocused = null;
  }

  function showError(message) {
    els.eventError.textContent = message;
    els.eventError.hidden = false;
  }

  function submit(submitEvent) {
    submitEvent.preventDefault();
    var title = els.eventTitle.value.trim();
    var date = els.eventDate.value;

    if (!title) return showError('Give the event a title.');
    // Safari on older iOS has no date picker widget, so validate the text.
    if (!Store.isKey(date)) return showError('Pick a valid date.');
    if (els.until.value && !Store.isKey(els.until.value)) return showError('Pick a valid end date.');
    if (els.repeat.value && els.until.value && els.until.value < date) {
      return showError('The repeat cannot end before it starts.');
    }

    var scope = currentScope();
    Store.saveEvent({
      id: editingId,
      scope: scope,
      occurrenceDate: occurrenceDate,
      title: title,
      date: date,
      time: els.eventTime.value || '',
      details: els.eventDetails.value.trim(),
      repeat: els.repeat.value,
      repeatUntil: els.repeat.value ? els.until.value : '',
      // A new rule makes the old list of skipped days meaningless.
      resetSkips: !!(editingMaster && editingMaster.repeat !== els.repeat.value)
    });

    selectedDate = date;
    var moved = Store.fromKey(date);
    viewMonth = new Date(moved.getFullYear(), moved.getMonth(), 1);
    closeModal();
    render();
  }

  function removeEvent() {
    if (!editingId) return;
    var repeating = editingMaster && editingMaster.repeat;
    var scope = repeating ? currentScope() : 'series';

    var message = repeating && scope === 'occurrence'
      ? 'Remove just this day from the series?'
      : (repeating ? 'Delete the whole repeating event?' : 'Delete this event?');
    if (!window.confirm(message)) return;

    Store.deleteEvent(editingId, scope, occurrenceDate);
    closeModal();
    render();
  }

  /* ----------------------------------------------------------------- api -- */

  function init() {
    els = {
      grid: document.getElementById('day-grid'),
      weekdays: document.getElementById('weekday-row'),
      monthLabel: document.getElementById('month-label'),
      dayLabel: document.getElementById('day-label'),
      dayEvents: document.getElementById('day-events'),
      dayTasks: document.getElementById('day-tasks'),
      dayTasksWrap: document.getElementById('day-tasks-wrap'),
      modal: document.getElementById('event-modal'),
      modalTitle: document.getElementById('event-modal-title'),
      eventTitle: document.getElementById('event-title'),
      eventDate: document.getElementById('event-date'),
      eventTime: document.getElementById('event-time'),
      eventDetails: document.getElementById('event-details'),
      eventDelete: document.getElementById('event-delete'),
      eventError: document.getElementById('event-error'),
      repeat: document.getElementById('event-repeat'),
      until: document.getElementById('event-until'),
      scope: document.getElementById('event-scope')
    };

    selectedDate = Store.todayKey();
    viewMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);

    renderWeekdays();
    TasksView.wireList(els.dayTasks);

    // Rotating a phone switches between the long and short day label.
    if (narrow.addEventListener) narrow.addEventListener('change', renderDayPanel);
    else if (narrow.addListener) narrow.addListener(renderDayPanel);

    document.getElementById('prev-month').addEventListener('click', function () {
      viewMonth = new Date(viewMonth.getFullYear(), viewMonth.getMonth() - 1, 1);
      render();
    });
    document.getElementById('next-month').addEventListener('click', function () {
      viewMonth = new Date(viewMonth.getFullYear(), viewMonth.getMonth() + 1, 1);
      render();
    });
    document.getElementById('add-event').addEventListener('click', function () {
      openModal(null, selectedDate);
    });

    els.grid.addEventListener('click', function (clickEvent) {
      var cell = clickEvent.target.closest('.day');
      if (!cell) return;
      selectedDate = cell.dataset.date;
      var date = Store.fromKey(selectedDate);
      if (date.getMonth() !== viewMonth.getMonth() || date.getFullYear() !== viewMonth.getFullYear()) {
        viewMonth = new Date(date.getFullYear(), date.getMonth(), 1);
      }
      render();
    });

    els.grid.addEventListener('dblclick', function (clickEvent) {
      var cell = clickEvent.target.closest('.day');
      if (cell) openModal(null, cell.dataset.date);
    });

    els.dayEvents.addEventListener('click', function (clickEvent) {
      var item = clickEvent.target.closest('.event-item');
      if (item) openModal(item.dataset.id, selectedDate, selectedDate);
    });

    els.repeat.addEventListener('change', syncUntilField);

    // Switching between "this day" and "the series" changes which date the
    // form is really editing.
    els.scope.addEventListener('change', function () {
      if (!editingMaster) return;
      els.eventDate.value = currentScope() === 'series' ? editingMaster.date : occurrenceDate;
    });

    document.getElementById('event-form').addEventListener('submit', submit);
    document.getElementById('event-cancel').addEventListener('click', closeModal);
    els.eventDelete.addEventListener('click', removeEvent);
    els.modal.addEventListener('mousedown', function (clickEvent) {
      if (clickEvent.target === els.modal) closeModal();
    });

    render();
  }

  return {
    init: init,
    render: render,
    isModalOpen: function () { return !els.modal.hidden; },
    closeModal: closeModal,
    goToday: function () {
      var now = new Date();
      selectedDate = Store.toKey(now);
      viewMonth = new Date(now.getFullYear(), now.getMonth(), 1);
      render();
    },
    selectDate: function (key) {
      selectedDate = key;
      var date = Store.fromKey(key);
      viewMonth = new Date(date.getFullYear(), date.getMonth(), 1);
      render();
    },
    newEvent: function (dateKey) { openModal(null, dateKey || selectedDate); },
    editEvent: function (id, date) { openModal(id, date, date); }
  };
})();
