/* The city list behind the Timezones screen.

   Each entry is [city, area, IANA zone]. Cities sharing a zone are listed
   separately on purpose — you look up "San Diego", not "America/Los_Angeles" —
   and `area` carries the state or country so searching "California" or "Japan"
   finds them all.

   Offsets are never stored here. Intl works them out from the zone at display
   time, so daylight saving is always right and the list never goes stale.
*/
window.ZONES = [
  /* ---------------------------------------------------- United States -- */
  ['Los Angeles', 'California, USA', 'America/Los_Angeles'],
  ['San Francisco', 'California, USA', 'America/Los_Angeles'],
  ['San Diego', 'California, USA', 'America/Los_Angeles'],
  ['San Jose', 'California, USA', 'America/Los_Angeles'],
  ['Sacramento', 'California, USA', 'America/Los_Angeles'],
  ['Fresno', 'California, USA', 'America/Los_Angeles'],
  ['Oakland', 'California, USA', 'America/Los_Angeles'],
  ['Seattle', 'Washington, USA', 'America/Los_Angeles'],
  ['Portland', 'Oregon, USA', 'America/Los_Angeles'],
  ['Las Vegas', 'Nevada, USA', 'America/Los_Angeles'],
  ['Reno', 'Nevada, USA', 'America/Los_Angeles'],
  ['Phoenix', 'Arizona, USA', 'America/Phoenix'],
  ['Tucson', 'Arizona, USA', 'America/Phoenix'],
  ['Denver', 'Colorado, USA', 'America/Denver'],
  ['Colorado Springs', 'Colorado, USA', 'America/Denver'],
  ['Salt Lake City', 'Utah, USA', 'America/Denver'],
  ['Albuquerque', 'New Mexico, USA', 'America/Denver'],
  ['Boise', 'Idaho, USA', 'America/Boise'],
  ['Chicago', 'Illinois, USA', 'America/Chicago'],
  ['Houston', 'Texas, USA', 'America/Chicago'],
  ['Dallas', 'Texas, USA', 'America/Chicago'],
  ['Austin', 'Texas, USA', 'America/Chicago'],
  ['San Antonio', 'Texas, USA', 'America/Chicago'],
  ['Minneapolis', 'Minnesota, USA', 'America/Chicago'],
  ['Kansas City', 'Missouri, USA', 'America/Chicago'],
  ['St. Louis', 'Missouri, USA', 'America/Chicago'],
  ['New Orleans', 'Louisiana, USA', 'America/Chicago'],
  ['Nashville', 'Tennessee, USA', 'America/Chicago'],
  ['Memphis', 'Tennessee, USA', 'America/Chicago'],
  ['Milwaukee', 'Wisconsin, USA', 'America/Chicago'],
  ['New York', 'New York, USA', 'America/New_York'],
  ['Brooklyn', 'New York, USA', 'America/New_York'],
  ['Buffalo', 'New York, USA', 'America/New_York'],
  ['Boston', 'Massachusetts, USA', 'America/New_York'],
  ['Philadelphia', 'Pennsylvania, USA', 'America/New_York'],
  ['Pittsburgh', 'Pennsylvania, USA', 'America/New_York'],
  ['Washington DC', 'USA', 'America/New_York'],
  ['Baltimore', 'Maryland, USA', 'America/New_York'],
  ['Atlanta', 'Georgia, USA', 'America/New_York'],
  ['Miami', 'Florida, USA', 'America/New_York'],
  ['Orlando', 'Florida, USA', 'America/New_York'],
  ['Tampa', 'Florida, USA', 'America/New_York'],
  ['Charlotte', 'North Carolina, USA', 'America/New_York'],
  ['Detroit', 'Michigan, USA', 'America/Detroit'],
  ['Cleveland', 'Ohio, USA', 'America/New_York'],
  ['Columbus', 'Ohio, USA', 'America/New_York'],
  ['Indianapolis', 'Indiana, USA', 'America/Indiana/Indianapolis'],
  ['Anchorage', 'Alaska, USA', 'America/Anchorage'],
  ['Honolulu', 'Hawaii, USA', 'Pacific/Honolulu'],

  /* ------------------------------------------------------------ Canada -- */
  ['Vancouver', 'British Columbia, Canada', 'America/Vancouver'],
  ['Victoria', 'British Columbia, Canada', 'America/Vancouver'],
  ['Calgary', 'Alberta, Canada', 'America/Edmonton'],
  ['Edmonton', 'Alberta, Canada', 'America/Edmonton'],
  ['Winnipeg', 'Manitoba, Canada', 'America/Winnipeg'],
  ['Toronto', 'Ontario, Canada', 'America/Toronto'],
  ['Ottawa', 'Ontario, Canada', 'America/Toronto'],
  ['Montreal', 'Quebec, Canada', 'America/Toronto'],
  ['Quebec City', 'Quebec, Canada', 'America/Toronto'],
  ['Halifax', 'Nova Scotia, Canada', 'America/Halifax'],
  ["St. John's", 'Newfoundland, Canada', 'America/St_Johns'],

  /* -------------------------------------------- Mexico, Central America -- */
  ['Mexico City', 'Mexico', 'America/Mexico_City'],
  ['Guadalajara', 'Mexico', 'America/Mexico_City'],
  ['Monterrey', 'Mexico', 'America/Monterrey'],
  ['Cancún', 'Mexico', 'America/Cancun'],
  ['Tijuana', 'Mexico', 'America/Tijuana'],
  ['Guatemala City', 'Guatemala', 'America/Guatemala'],
  ['San Salvador', 'El Salvador', 'America/El_Salvador'],
  ['San José', 'Costa Rica', 'America/Costa_Rica'],
  ['Panama City', 'Panama', 'America/Panama'],
  ['Havana', 'Cuba', 'America/Havana'],
  ['Kingston', 'Jamaica', 'America/Jamaica'],
  ['Santo Domingo', 'Dominican Republic', 'America/Santo_Domingo'],
  ['San Juan', 'Puerto Rico', 'America/Puerto_Rico'],

  /* ----------------------------------------------------- South America -- */
  ['Bogotá', 'Colombia', 'America/Bogota'],
  ['Medellín', 'Colombia', 'America/Bogota'],
  ['Lima', 'Peru', 'America/Lima'],
  ['Quito', 'Ecuador', 'America/Guayaquil'],
  ['Caracas', 'Venezuela', 'America/Caracas'],
  ['La Paz', 'Bolivia', 'America/La_Paz'],
  ['Santiago', 'Chile', 'America/Santiago'],
  ['Buenos Aires', 'Argentina', 'America/Argentina/Buenos_Aires'],
  ['Córdoba', 'Argentina', 'America/Argentina/Cordoba'],
  ['Montevideo', 'Uruguay', 'America/Montevideo'],
  ['Asunción', 'Paraguay', 'America/Asuncion'],
  ['São Paulo', 'Brazil', 'America/Sao_Paulo'],
  ['Rio de Janeiro', 'Brazil', 'America/Sao_Paulo'],
  ['Brasília', 'Brazil', 'America/Sao_Paulo'],
  ['Manaus', 'Brazil', 'America/Manaus'],

  /* ------------------------------------------------------------ Europe -- */
  ['London', 'United Kingdom', 'Europe/London'],
  ['Manchester', 'United Kingdom', 'Europe/London'],
  ['Birmingham', 'United Kingdom', 'Europe/London'],
  ['Edinburgh', 'Scotland, UK', 'Europe/London'],
  ['Glasgow', 'Scotland, UK', 'Europe/London'],
  ['Cardiff', 'Wales, UK', 'Europe/London'],
  ['Belfast', 'Northern Ireland, UK', 'Europe/London'],
  ['Dublin', 'Ireland', 'Europe/Dublin'],
  ['Lisbon', 'Portugal', 'Europe/Lisbon'],
  ['Porto', 'Portugal', 'Europe/Lisbon'],
  ['Madrid', 'Spain', 'Europe/Madrid'],
  ['Barcelona', 'Spain', 'Europe/Madrid'],
  ['Valencia', 'Spain', 'Europe/Madrid'],
  ['Paris', 'France', 'Europe/Paris'],
  ['Lyon', 'France', 'Europe/Paris'],
  ['Marseille', 'France', 'Europe/Paris'],
  ['Nice', 'France', 'Europe/Paris'],
  ['Brussels', 'Belgium', 'Europe/Brussels'],
  ['Amsterdam', 'Netherlands', 'Europe/Amsterdam'],
  ['Rotterdam', 'Netherlands', 'Europe/Amsterdam'],
  ['Luxembourg', 'Luxembourg', 'Europe/Luxembourg'],
  ['Berlin', 'Germany', 'Europe/Berlin'],
  ['Munich', 'Germany', 'Europe/Berlin'],
  ['Frankfurt', 'Germany', 'Europe/Berlin'],
  ['Hamburg', 'Germany', 'Europe/Berlin'],
  ['Cologne', 'Germany', 'Europe/Berlin'],
  ['Zurich', 'Switzerland', 'Europe/Zurich'],
  ['Geneva', 'Switzerland', 'Europe/Zurich'],
  ['Vienna', 'Austria', 'Europe/Vienna'],
  ['Milan', 'Italy', 'Europe/Rome'],
  ['Rome', 'Italy', 'Europe/Rome'],
  ['Naples', 'Italy', 'Europe/Rome'],
  ['Venice', 'Italy', 'Europe/Rome'],
  ['Copenhagen', 'Denmark', 'Europe/Copenhagen'],
  ['Oslo', 'Norway', 'Europe/Oslo'],
  ['Stockholm', 'Sweden', 'Europe/Stockholm'],
  ['Gothenburg', 'Sweden', 'Europe/Stockholm'],
  ['Helsinki', 'Finland', 'Europe/Helsinki'],
  ['Reykjavík', 'Iceland', 'Atlantic/Reykjavik'],
  ['Prague', 'Czechia', 'Europe/Prague'],
  ['Warsaw', 'Poland', 'Europe/Warsaw'],
  ['Kraków', 'Poland', 'Europe/Warsaw'],
  ['Budapest', 'Hungary', 'Europe/Budapest'],
  ['Bratislava', 'Slovakia', 'Europe/Bratislava'],
  ['Ljubljana', 'Slovenia', 'Europe/Ljubljana'],
  ['Zagreb', 'Croatia', 'Europe/Zagreb'],
  ['Belgrade', 'Serbia', 'Europe/Belgrade'],
  ['Bucharest', 'Romania', 'Europe/Bucharest'],
  ['Sofia', 'Bulgaria', 'Europe/Sofia'],
  ['Athens', 'Greece', 'Europe/Athens'],
  ['Istanbul', 'Türkiye', 'Europe/Istanbul'],
  ['Ankara', 'Türkiye', 'Europe/Istanbul'],
  ['Kyiv', 'Ukraine', 'Europe/Kyiv'],
  ['Minsk', 'Belarus', 'Europe/Minsk'],
  ['Riga', 'Latvia', 'Europe/Riga'],
  ['Vilnius', 'Lithuania', 'Europe/Vilnius'],
  ['Tallinn', 'Estonia', 'Europe/Tallinn'],
  ['Moscow', 'Russia', 'Europe/Moscow'],
  ['Saint Petersburg', 'Russia', 'Europe/Moscow'],
  ['Yekaterinburg', 'Russia', 'Asia/Yekaterinburg'],
  ['Novosibirsk', 'Russia', 'Asia/Novosibirsk'],
  ['Vladivostok', 'Russia', 'Asia/Vladivostok'],
  ['Malta', 'Malta', 'Europe/Malta'],

  /* ------------------------------------------------------ Africa, Middle East -- */
  ['Casablanca', 'Morocco', 'Africa/Casablanca'],
  ['Algiers', 'Algeria', 'Africa/Algiers'],
  ['Tunis', 'Tunisia', 'Africa/Tunis'],
  ['Cairo', 'Egypt', 'Africa/Cairo'],
  ['Lagos', 'Nigeria', 'Africa/Lagos'],
  ['Abuja', 'Nigeria', 'Africa/Lagos'],
  ['Accra', 'Ghana', 'Africa/Accra'],
  ['Dakar', 'Senegal', 'Africa/Dakar'],
  ['Addis Ababa', 'Ethiopia', 'Africa/Addis_Ababa'],
  ['Nairobi', 'Kenya', 'Africa/Nairobi'],
  ['Kampala', 'Uganda', 'Africa/Kampala'],
  ['Dar es Salaam', 'Tanzania', 'Africa/Dar_es_Salaam'],
  ['Kinshasa', 'DR Congo', 'Africa/Kinshasa'],
  ['Luanda', 'Angola', 'Africa/Luanda'],
  ['Harare', 'Zimbabwe', 'Africa/Harare'],
  ['Johannesburg', 'South Africa', 'Africa/Johannesburg'],
  ['Cape Town', 'South Africa', 'Africa/Johannesburg'],
  ['Durban', 'South Africa', 'Africa/Johannesburg'],
  ['Tel Aviv', 'Israel', 'Asia/Jerusalem'],
  ['Jerusalem', 'Israel', 'Asia/Jerusalem'],
  ['Beirut', 'Lebanon', 'Asia/Beirut'],
  ['Amman', 'Jordan', 'Asia/Amman'],
  ['Damascus', 'Syria', 'Asia/Damascus'],
  ['Baghdad', 'Iraq', 'Asia/Baghdad'],
  ['Riyadh', 'Saudi Arabia', 'Asia/Riyadh'],
  ['Jeddah', 'Saudi Arabia', 'Asia/Riyadh'],
  ['Doha', 'Qatar', 'Asia/Qatar'],
  ['Kuwait City', 'Kuwait', 'Asia/Kuwait'],
  ['Manama', 'Bahrain', 'Asia/Bahrain'],
  ['Dubai', 'United Arab Emirates', 'Asia/Dubai'],
  ['Abu Dhabi', 'United Arab Emirates', 'Asia/Dubai'],
  ['Muscat', 'Oman', 'Asia/Muscat'],
  ['Tehran', 'Iran', 'Asia/Tehran'],
  ['Baku', 'Azerbaijan', 'Asia/Baku'],
  ['Tbilisi', 'Georgia', 'Asia/Tbilisi'],
  ['Yerevan', 'Armenia', 'Asia/Yerevan'],

  /* -------------------------------------------------------------- Asia -- */
  ['Karachi', 'Pakistan', 'Asia/Karachi'],
  ['Lahore', 'Pakistan', 'Asia/Karachi'],
  ['Islamabad', 'Pakistan', 'Asia/Karachi'],
  ['Kabul', 'Afghanistan', 'Asia/Kabul'],
  ['Tashkent', 'Uzbekistan', 'Asia/Tashkent'],
  ['Almaty', 'Kazakhstan', 'Asia/Almaty'],
  ['Delhi', 'India', 'Asia/Kolkata'],
  ['Mumbai', 'India', 'Asia/Kolkata'],
  ['Bengaluru', 'India', 'Asia/Kolkata'],
  ['Chennai', 'India', 'Asia/Kolkata'],
  ['Hyderabad', 'India', 'Asia/Kolkata'],
  ['Kolkata', 'India', 'Asia/Kolkata'],
  ['Colombo', 'Sri Lanka', 'Asia/Colombo'],
  ['Kathmandu', 'Nepal', 'Asia/Kathmandu'],
  ['Dhaka', 'Bangladesh', 'Asia/Dhaka'],
  ['Yangon', 'Myanmar', 'Asia/Yangon'],
  ['Bangkok', 'Thailand', 'Asia/Bangkok'],
  ['Phuket', 'Thailand', 'Asia/Bangkok'],
  ['Hanoi', 'Vietnam', 'Asia/Ho_Chi_Minh'],
  ['Ho Chi Minh City', 'Vietnam', 'Asia/Ho_Chi_Minh'],
  ['Phnom Penh', 'Cambodia', 'Asia/Phnom_Penh'],
  ['Vientiane', 'Laos', 'Asia/Vientiane'],
  ['Singapore', 'Singapore', 'Asia/Singapore'],
  ['Kuala Lumpur', 'Malaysia', 'Asia/Kuala_Lumpur'],
  ['Penang', 'Malaysia', 'Asia/Kuala_Lumpur'],
  ['Johor Bahru', 'Malaysia', 'Asia/Kuala_Lumpur'],
  ['Jakarta', 'Indonesia', 'Asia/Jakarta'],
  ['Bali (Denpasar)', 'Indonesia', 'Asia/Makassar'],
  ['Manila', 'Philippines', 'Asia/Manila'],
  ['Cebu', 'Philippines', 'Asia/Manila'],
  ['Hong Kong', 'Hong Kong', 'Asia/Hong_Kong'],
  ['Macau', 'Macau', 'Asia/Macau'],
  ['Taipei', 'Taiwan', 'Asia/Taipei'],
  ['Beijing', 'China', 'Asia/Shanghai'],
  ['Shanghai', 'China', 'Asia/Shanghai'],
  ['Shenzhen', 'China', 'Asia/Shanghai'],
  ['Guangzhou', 'China', 'Asia/Shanghai'],
  ['Chengdu', 'China', 'Asia/Shanghai'],
  ['Ulaanbaatar', 'Mongolia', 'Asia/Ulaanbaatar'],
  ['Seoul', 'South Korea', 'Asia/Seoul'],
  ['Busan', 'South Korea', 'Asia/Seoul'],
  ['Tokyo', 'Japan', 'Asia/Tokyo'],
  ['Osaka', 'Japan', 'Asia/Tokyo'],
  ['Kyoto', 'Japan', 'Asia/Tokyo'],
  ['Sapporo', 'Japan', 'Asia/Tokyo'],

  /* --------------------------------------------------- Oceania, Pacific -- */
  ['Perth', 'Western Australia', 'Australia/Perth'],
  ['Adelaide', 'South Australia', 'Australia/Adelaide'],
  ['Darwin', 'Northern Territory, Australia', 'Australia/Darwin'],
  ['Brisbane', 'Queensland, Australia', 'Australia/Brisbane'],
  ['Gold Coast', 'Queensland, Australia', 'Australia/Brisbane'],
  ['Cairns', 'Queensland, Australia', 'Australia/Brisbane'],
  ['Sydney', 'New South Wales, Australia', 'Australia/Sydney'],
  ['Canberra', 'Australia', 'Australia/Sydney'],
  ['Melbourne', 'Victoria, Australia', 'Australia/Melbourne'],
  ['Hobart', 'Tasmania, Australia', 'Australia/Hobart'],
  ['Auckland', 'New Zealand', 'Pacific/Auckland'],
  ['Wellington', 'New Zealand', 'Pacific/Auckland'],
  ['Christchurch', 'New Zealand', 'Pacific/Auckland'],
  ['Suva', 'Fiji', 'Pacific/Fiji'],
  ['Port Moresby', 'Papua New Guinea', 'Pacific/Port_Moresby'],
  ['Nouméa', 'New Caledonia', 'Pacific/Noumea'],
  ['Apia', 'Samoa', 'Pacific/Apia'],
  ['Papeete', 'French Polynesia', 'Pacific/Tahiti'],
  ['Guam', 'Guam', 'Pacific/Guam'],

  /* ------------------------------------------------------------- other -- */
  ['UTC', 'Coordinated Universal Time', 'UTC']
];
